### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Boomflex** [ProfessorProspector/Traverse#1]
https://pastebin.com/F8NgQT5B

Caused by: java.lang.NullPointerException
	at prospector.traverse.config.TraverseConfig.reloadVersionConfig(TraverseConfig.java:105)

traverse{1.11.2-1.1.1-20}
FML(forge-1.11.2-13.20.0.2314-universal.jar)

**Comment by ProfessorProspector** [comment]
Ah, shoot. I really need to redo this stupid instance version thing I did and make it per-world.

**Comment by ProfessorProspector** [comment]
Oh, is this on a server?

**Comment by ProfessorProspector** [comment]
This should be fixed in v1.1.2, but I still should make it per-world. Probably will for v1.2. If this issue wasn't on a server, or isn't fixed, please update here.
