### ISSUE TITLE
TODO: Add config to disable custom sky colours

### ISSUE THREAD

**Issue by billybricker** [ProfessorProspector/Traverse#3]
I've noticed the sky goes very white whenever I'm in a Traverse biome. Not sure if this is intended but I assume it isn't.

http://imgur.com/a/kX6Ml

Forge: 14.21.0.2343
Traverse: v1.1.7 build11 (but I noticed it in previous versions as well)

**Comment by ProfessorProspector** [comment]
This is intended, a few of the biomes have different sky colours. I can add a config if you wish? I may also tweak the default values but I quite like them personally, especially the reddish sky in a Red Desert and the greenish one in the Mini Jungle.

**Comment by billybricker** [comment]
I think colors would be nice but as it stands the sky is just white in any Traverse biomes. I haven't noticed any other colors. I did notice, after further testing, that it seems to be less prominent with graphics set to fancy, but when set to fast it's a really jarring change from the normal blue to pure white.

**Comment by ProfessorProspector** [comment]
Huh, I wonder if it is an issue with forge and the fast setting. If it is, I can disable them automatically on fast? I'll look into it further. Thanks for bringing it to my attention.

**Comment by billybricker** [comment]
It's possible it could be a forge issue. It's been happening with every version of forge I've tested on 1.12. I can check the 1.11 version after dinner and see if it's happening there as well. 

Config options couldn't hurt either, if they're not too hard to add, at least for testing purposes until 1.12 stabilizes.

**Comment by ProfessorProspector** [comment]
I would imagine it is the case on 1.11 too, seeing as that other guy on Reddit pointed it out. I'll definitely be adding a config and backporting it to 1.11 as well. Might even put the config on by default.

**Comment by billybricker** [comment]
Fair point. I will say I tested this with only Forge and Traverse installed to make sure it was on your end before I opened this issue, so if it's not you then I'd say something is wrong with Forge and the fast graphics option. I haven't noticed this with any other mod though, might require more testing once more biome and dimension mods get ported.

**Comment by billybricker** [comment]
During further testing, on an unrelated issue that I can't seem to replicate with only Traverse installed so yay for that, the mini jungle seems to have a greenish sky.

http://imgur.com/a/TRkJF

It's the only one I've seen so far that has color. The other biomes I found in that world were white.

**Comment by InsomniaKitten** [comment]
@ProfessorProspector If you're changing the sky color you should be changing the fog color too, otherwise it clashes worse that vanilla fog against vanilla sky. 😜

**Comment by ProfessorProspector** [comment]
@billybricker Okay so I found something, apparently the sky colour in the Meadow and Lush Swamp *were* being set to an almost white colour, this has been fixed. However, these biomes all looked fine to me and I wasn't able to replicate them.

![image](https://user-images.githubusercontent.com/6166773/27436582-936b0412-5714-11e7-8a89-f1e12ab2eb97.png)

![image](https://user-images.githubusercontent.com/6166773/27436588-983d15a2-5714-11e7-9d13-11929766f1c3.png)

![image](https://user-images.githubusercontent.com/6166773/27436625-b4e11ba4-5714-11e7-96fe-a6e302b5713a.png)

![image](https://user-images.githubusercontent.com/6166773/27436630-ba5ecbda-5714-11e7-9f5c-1e0be3b3ff77.png)

Can you confirm every biome you had this issue with? Also, did you happen to be on a very low render distance?

**Comment by ProfessorProspector** [comment]
There will be a config for this in the next release.

**Comment by billybricker** [comment]
The mini jungle was the only one I saw any color in. Autumnal woods, lush swamp, and meadows I know for sure were white in my lay test world. I don't believe I changed the render distance but I can check that and make a better list of affected biomes after work.

**Comment by croftyraider** [comment]
My render distance is 12 and I use fancy graphics, for what it's worth. I also did not see any sky coloration other than white.

**Comment by ProfessorProspector** [comment]
Shoot I didn't mean to delete that. It said "My render distance is 12 and I use fancy graphics, for what it's worth. I also did not see any sky coloration other than white."

Try disabling the custom sky colours in the latest version (it's on

**Comment by croftyraider** [comment]
No undelete eh? Ah well, anyway I should have also mentioned I am playing with 1.11.2 so I'm guessing you're not backporting that config option? Thanks for adding in the option :)

**Comment by ProfessorProspector** [comment]
The config is backported, I released it alongside 1.2 this morning.

**Comment by croftyraider** [comment]
One more question - I've been playing with Traverse version 1.11.2-1.0.0-8

Is my world going to get screwed up if update to your fixed version? If so, in what way? thanks :)

**Comment by ProfessorProspector** [comment]
It *should* be fine but there is one thing you need to do first. You need to update to v1.0.2 BEFORE updating to anything newer. So update to 1.0.2, run the game, and then you should be able to update to the latest.

**Comment by billybricker** [comment]
Well I went to check some other biomes with the versions I mentioned in the OP they all seem to have color to them now. No clue what was causing them all to be white, I don't think I changed anything apart from fiddling with the graphics settings a bit. Either way thanks for the help, and the config option. :)

**Comment by croftyraider** [comment]
Just thought I would report back - skies are fixed, and doing your 2 step upgrade worked beautifully - I went on a large exploration trip in my world (looking for Pam's peppercorn tree) and didn't see any terrain goofs, so thanks!
