### ISSUE TITLE
Suggestion: Compile Deobf Jar

### ISSUE THREAD

**Issue by BlackJar72** [ProfessorProspector/Traverse#35]
I've been working on a biome-placement mod / modded biome provider.  I've already added BoP support, but would like to add built in Traverse support as well.  You seem be using your own Gradle scripts (I'm not a Gradle expert, but I can see they aren't the ones from Forge), and I'm not quite sure how to modify them.  Do you think you could add a deobf to the compilation, it would really help to be able to reference this mod in eclipse without including all of its source code.

Thanks.

**Comment by modmuss50** [comment]
You can use `deobfCompile` in gradle, this will automatically create you a debof jar that is also on the correct mappings.

There is no need for debof jars anymore (since a few years ago)

Traverse is on my maven http://maven.modmuss50.me/prospector/traverse/Traverse/ so you can easily include it in your build.gradle

**Comment by BlackJar72** [comment]
Well, I meant include an obvious way to compile one in the build.gradle -- I can do this with some build scripts, but don't know how to with yours (I'm far from a Gradle expert).

**Comment by ProfessorProspector** [comment]
Add this to your repositories block in your build.gradle:

`maven {
		name = "Modmuss50"
		url = "http://maven.modmuss50.me/"
	}`

This adds modmuss' maven repo to your script so you can access files hosted on it. 

Then add this to your dependencies block:
`compile 'prospector.traverse:Traverse-1.12.2-1.6.1-71'`

That should work

**Comment by BlackJar72** [comment]
OK, thanks, I'll try that.  I was going to add a user config system anyone -- if this doesn't work I'll just drop out-of-the-box support and players can add your biomes that way.

**Comment by BlackJar72** [comment]
I just wanted to make it easy to use with a few of the more popular biome mods -- some players love maximum control, but many want things to just automatically work and assume it will.

**Comment by ProfessorProspector** [comment]
What do you need to call Traverse's code for if you can do everything with a config? Why not just ship default configs with traverse and biomes o plenty and stuff?
