### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [ProfessorProspector/Traverse#5]
I'm not 100% sure this is your issue, but when i click on view more after crash it says caught exception from traverse. This happened on your past 2 updates with the newest forge at the time. I thought maybe another mod wasn't updated with the forge changes, but I tried to fumble through the crash report for a more exact answer but I couldn't see one that I could understand. Anywho, here is the report, sorry in advance if its not your issue.

https://pastebin.com/GHp61Tsr

**Comment by InsomniaKitten** [comment]
Please update to latest OptiFine to prevent this crash. The latest compatible release can be found here, which should solve your issue. 

[optifine.net/preview_OptiFine_1.12_HD_U_C4_pre.jar](http://optifine.net/adloadx?f=preview_OptiFine_1.12_HD_U_C4_pre.jar)
