### ISSUE TITLE
Crash With Latest Forge (2387)

### ISSUE THREAD

**Issue by kenijey** [ProfessorProspector/Traverse#6]
[crash-2017-07-02_15.04.58-client.txt](https://github.com/ProfessorProspector/Traverse/files/1117772/crash-2017-07-02_15.04.58-client.txt)

**Comment by ProfessorProspector** [comment]
You're on a pretty old version. Update to 1.2.1 build22 which you can find [here](https://minecraft.curseforge.com/projects/traverse/files/2441066)

**Comment by kenijey** [comment]
oh, sorry. dunno why i didn't update it, i everytime follow latest updates of mods.
